//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTOR
    {
        public int sec_id { get; set; }
        public string sec_name { get; set; }
        public Nullable<int> threshold { get; set; }
        public string lat_long { get; set; }
    }
}
