//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYP_Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int user_id { get; set; }
        public Nullable<int> sec_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string password { get; set; }
        public string role { get; set; }
        public string image { get; set; }
        public string home_location { get; set; }
        public string office_location { get; set; }
    }
}
